### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by soulnous**

### CODE REVIEW

**Comment by drogga** [comment]
@soulnous Nope, wrong, nobody wants it to always run and be restricted in landscape only on everything, remove the whole `screenOrientation` line instead, as it's unnecessary.
@prateek-chaubey can merge after. ;)

**Comment by drogga** [comment]
@prateek-chaubey can you please finally merge these PRs, there shouldn't be conflicts I think, let's not keep them open for years (like in some repos), because there's a chance that people will lose interest and start deleting their patches and close their PRs, or at least make someone a collaborator/member or whatever with permission to carry on the project...
As of this one in particular: It's probably created with the `Allow edits by maintainers` option enabled, so you should be easily able to edit it and merge (if the author doesn't want to for some reason) or at least close it, as in its current state it's pointless.

Thank You and I hope that you see this (if you do, please react with an emoji, like 'eyes' for example, so I know I'm not wasting my time in typing in vain) ;)

**Comment by drogga** [comment]
The `screenOrientation` was set to `fullSensor` in https://github.com/prateek-chaubey/YTPro/commit/6718172a9167bad98447c21f42b8a2950de4fe67 and in/with later commit https://github.com/prateek-chaubey/YTPro/commit/a19afe97a9b04ac8c313e7ad2f10e4d2707cbac6 was reverted back to `portrait`, I wonder why when I've tested it in landscape and it's not worse than being in portrait, so why forcing and restricting it everywhere, besides the player, where it rotates to landscape, you know that none of the other YT apps are with restricted orientation and that not everyone will use it on phones right ?

Oh and btw the gear icon button (for YT settings, like rez., speed, etc.) doesn't do anything in fullscreen when playing a video, but only in windowed mode, it's annoying the videos (and probably songs - those with only audio and a cove art) to start muted by default and the latest Actions build is dimmes, like there's a overlay filter or something, except when playing a video in fullscreen, which is odd.

@AbdurazaaqMohammed - You would probably want to know this as well ;)

**Comment by prateek-chaubey** [comment]
I have reverted the changes from `fullSensor` to `portrait` because it wasn't compatible with UX.

The gear icon of Youtube web app is like that only , i checked in different browsers and it's not working in them as well , it needs to be fixed by YouTube itself.

Can you elaborate more about the dim issue , maybe attach a screenshot.

Regarding the permissions , it will be updated in the next build , i guess i will add it the same way as it is for the microphone access.

**Comment by drogga** [comment]
Can you please show me some visuals on how and where it's incompatible with the UX ?

I just checked on the latest LTT video even in old ver. of Bromite and the gear settings button does bring the pop-up dialog no matter what, it even does add `#dialog` to the URL and removes it without refreshing when/once closed, no matter the orientation and it definitely works in full-screen (m.youtube.com)

I will see later if a screenshot or a video recording will capture properly or at all the dimming.

Regarding the permissions - OK, please do so asap and thanks in advance.

**Pull request closed without merging**
